### PR TITLE
Configured tslint and fixed style

### LINKED ISSUE #8: TSlint
Setup a TS lint for style standards. No strict restriction is required, simply reach consensus on a pleasant, easily readable and useful code style.

### PR DESCRIPTION
**Pull request by Gab05**
- Added tslint.json
- Custom rules, subject to change anytime for convenience
- Style fixing

Tip: Enable TSlint on Webstorm (automatic setup should find tslint.json at root of project)

closes #8

### CODE REVIEW

**Comment by GabCh** [comment]
I changed the App component declaration to match the function component declaration of react... We can also change it as a class component if it's better. Don't know what was wrong with the previous one but it was making the tests fail

**Comment by Gab05** [comment]
The PR #5 would've fixed the tests, but this is also valid! You could also specify the return type, which is a `JSX.Element`, but it doesn't really matter

**Comment by GabCh** [comment]
The old way does not seem to work @Gab05 can you confirm 10/4

**Comment by Gab05** [comment]
Will check after dinner - over.

**Comment by Gab05** [comment]
New tests seem successful! Ready to merge @GabCh

**Comment by GabCh** [comment]
Thanks buddy!

**Pull request merged**
